version: '3.0'

services:
  # pg:
  #   image: bitnami/postgresql:13.16.0
  #   ports:
  #     - '5432:5432'
  #   environment:
  #     - POSTGRES_USER=docker
  #     - POSTGRES_PASSWORD=docker
  #     - POSTGRES_DB=inorbit
  #   networks:
  #     - app-network
  #   volumes:
  #     - pgdata:/bitnami/postgresql 

  node-app-instance-1:
    build: .
    ports:
      - "3000:3000"  # Porta externa 3000 para a primeira instância
    networks:
      - app-network
    # depends_on:
      # - pg
  node-app-instance-2:
    build: .
    ports:
      - "3001:3000"  # Porta externa 3001 para a segunda instância
    networks:
      - app-network
    # depends_on:
      # - pg


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./devops/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - node-app-instance-1
      - node-app-instance-2
      # - pg
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    
# volumes:
#   pgdata: